receivers:
  sample:
    answerer_name: Arthur
    collection_interval: 10s

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers:
        - sample
      exporters:
        - debug
