// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sample")
	ScopeName = "github.com/Arthur1/opentelemetry-collector-components-tutorial/receiver/samplereceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
